<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE warehouses [
<!ELEMENT warehouses (warehouse*)>
<!ELEMENT warehouse (id, name, address, items)>
<!ELEMENT address (street, city, country)>
<!ELEMENT items (item*)>
<!ELEMENT item (id, im_id, name, price, qty)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT im_id (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT qty (#PCDATA)>
]>

<warehouses>
  <warehouse>
    <id>1</id>
    <name>DabZ</name>
    <address>
      <street>Green</street>
      <city>Patemon</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>10</qty>
      </item>
      <item>
        <id>6</id>
        <im_id>11822073</im_id>
        <name>miconazole 1</name>
        <price>73.35</price>
        <qty>522</qty>
      </item>
      <item>
        <id>10</id>
        <im_id>60429082</im_id>
        <name>Glipizide</name>
        <price>12.62</price>
        <qty>289</qty>
      </item>
      <item>
        <id>11</id>
        <im_id>50241141</im_id>
        <name>Skyline Antibacterial Hand Cleanser</name>
        <price>75.03</price>
        <qty>84</qty>
      </item>
      <item>
        <id>14</id>
        <im_id>36987288</im_id>
        <name>Virginia Live Oak</name>
        <price>36.96</price>
        <qty>99</qty>
      </item>
      <item>
        <id>15</id>
        <im_id>67510150</im_id>
        <name>Night Time Cold/Flu Relief Cherry</name>
        <price>92.26</price>
        <qty>140</qty>
      </item>
      <item>
        <id>17</id>
        <im_id>33992113</im_id>
        <name>anti-dandruff</name>
        <price>18.73</price>
        <qty>688</qty>
      </item>
      <item>
        <id>18</id>
        <im_id>53645147</im_id>
        <name>Ferrum Metallicum</name>
        <price>67.92</price>
        <qty>513</qty>
      </item>
      <item>
        <id>19</id>
        <im_id>44924010</im_id>
        <name>BABOR Baborganic Crystal Face Scrub</name>
        <price>21.95</price>
        <qty>157</qty>
      </item>
      <item>
        <id>25</id>
        <im_id>49288012</im_id>
        <name>Cattle Hair</name>
        <price>51.02</price>
        <qty>472</qty>
      </item>
      <item>
        <id>26</id>
        <im_id>68012054</im_id>
        <name>Zegerid</name>
        <price>17.08</price>
        <qty>103</qty>
      </item>
      <item>
        <id>27</id>
        <im_id>53942502</im_id>
        <name>NIGHT-TIME</name>
        <price>91.42</price>
        <qty>472</qty>
      </item>
      <item>
        <id>28</id>
        <im_id>49230191</im_id>
        <name>DELFLEX</name>
        <price>38.96</price>
        <qty>880</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>1</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>8</qty>
      </item>
      <item>
        <id>36</id>
        <im_id>29565200</im_id>
        <name>Sunscreen</name>
        <price>55.70</price>
        <qty>322</qty>
      </item>
      <item>
        <id>38</id>
        <im_id>62750003</im_id>
        <name>Zicam</name>
        <price>29.94</price>
        <qty>834</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>970</qty>
      </item>
      <item>
        <id>42</id>
        <im_id>42195210</im_id>
        <name>Pyrilamine Maleate and Phenylephrine Hydrochloride</name>
        <price>57.93</price>
        <qty>381</qty>
      </item>
      <item>
        <id>46</id>
        <im_id>05271905</im_id>
        <name>Zidovudine</name>
        <price>47.05</price>
        <qty>499</qty>
      </item>
      <item>
        <id>49</id>
        <im_id>60793701</im_id>
        <name>BICILLIN L-A</name>
        <price>55.58</price>
        <qty>774</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>2</id>
    <name>Skippad</name>
    <address>
      <street>Harper</street>
      <city>Makale</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>4</qty>
      </item>
      <item>
        <id>15</id>
        <im_id>67510150</im_id>
        <name>Night Time Cold/Flu Relief Cherry</name>
        <price>92.26</price>
        <qty>361</qty>
      </item>
      <item>
        <id>17</id>
        <im_id>33992113</im_id>
        <name>anti-dandruff</name>
        <price>18.73</price>
        <qty>936</qty>
      </item>
      <item>
        <id>18</id>
        <im_id>53645147</im_id>
        <name>Ferrum Metallicum</name>
        <price>67.92</price>
        <qty>435</qty>
      </item>
      <item>
        <id>19</id>
        <im_id>44924010</im_id>
        <name>BABOR Baborganic Crystal Face Scrub</name>
        <price>21.95</price>
        <qty>396</qty>
      </item>
      <item>
        <id>22</id>
        <im_id>59078034</im_id>
        <name>Tomatox Magic Massage Pack</name>
        <price>38.52</price>
        <qty>175</qty>
      </item>
      <item>
        <id>25</id>
        <im_id>49288012</im_id>
        <name>Cattle Hair</name>
        <price>51.02</price>
        <qty>27</qty>
      </item>
      <item>
        <id>29</id>
        <im_id>00934405</im_id>
        <name>Clozapine</name>
        <price>70.14</price>
        <qty>561</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>7</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>12</qty>
      </item>
      <item>
        <id>37</id>
        <im_id>64942122</im_id>
        <name>Dove Men plus Care</name>
        <price>41.28</price>
        <qty>989</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>373</qty>
      </item>
      <item>
        <id>40</id>
        <im_id>52959692</im_id>
        <name>misoprostol</name>
        <price>6.92</price>
        <qty>727</qty>
      </item>
      <item>
        <id>44</id>
        <im_id>76420780</im_id>
        <name>Multi-Specialty Kit</name>
        <price>23.04</price>
        <qty>744</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>3</id>
    <name>Briar Crest</name>
    <address>
      <street>Kensington</street>
      <city>Singapore</city>
      <country>Singapore</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>5</qty>
      </item>
      <item>
        <id>4</id>
        <im_id>54868007</im_id>
        <name>MECLIZINE HYDROCHLORIDE</name>
        <price>54.49</price>
        <qty>882</qty>
      </item>
      <item>
        <id>8</id>
        <im_id>60512629</im_id>
        <name>KALI BICHROMICUM</name>
        <price>15.60</price>
        <qty>286</qty>
      </item>
      <item>
        <id>9</id>
        <im_id>68788973</im_id>
        <name>TOPIRAMATE</name>
        <price>48.58</price>
        <qty>103</qty>
      </item>
      <item>
        <id>12</id>
        <im_id>00540097</im_id>
        <name>Oxcarbazepine</name>
        <price>18.86</price>
        <qty>584</qty>
      </item>
      <item>
        <id>14</id>
        <im_id>36987288</im_id>
        <name>Virginia Live Oak</name>
        <price>36.96</price>
        <qty>711</qty>
      </item>
      <item>
        <id>18</id>
        <im_id>53645147</im_id>
        <name>Ferrum Metallicum</name>
        <price>67.92</price>
        <qty>502</qty>
      </item>
      <item>
        <id>19</id>
        <im_id>44924010</im_id>
        <name>BABOR Baborganic Crystal Face Scrub</name>
        <price>21.95</price>
        <qty>979</qty>
      </item>
      <item>
        <id>22</id>
        <im_id>59078034</im_id>
        <name>Tomatox Magic Massage Pack</name>
        <price>38.52</price>
        <qty>356</qty>
      </item>
      <item>
        <id>23</id>
        <im_id>63354871</im_id>
        <name>BANANA BOAT</name>
        <price>98.86</price>
        <qty>163</qty>
      </item>
      <item>
        <id>30</id>
        <im_id>05361945</im_id>
        <name>RULOX REGULAR</name>
        <price>17.76</price>
        <qty>380</qty>
      </item>
      <item>
        <id>31</id>
        <im_id>52125461</im_id>
        <name>GENTAMICIN SULFATE</name>
        <price>93.43</price>
        <qty>394</qty>
      </item>
      <item>
        <id>32</id>
        <im_id>68012490</im_id>
        <name>Fenoglide</name>
        <price>41.31</price>
        <qty>922</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>4</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>19</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>125</qty>
      </item>
      <item>
        <id>43</id>
        <im_id>52959613</im_id>
        <name>Amoxicillin</name>
        <price>27.50</price>
        <qty>985</qty>
      </item>
      <item>
        <id>44</id>
        <im_id>76420780</im_id>
        <name>Multi-Specialty Kit</name>
        <price>23.04</price>
        <qty>534</qty>
      </item>
      <item>
        <id>48</id>
        <im_id>04060366</im_id>
        <name>HYDROCODONE BITARTRATE AND ACETAMINOPHEN</name>
        <price>54.18</price>
        <qty>760</qty>
      </item>
      <item>
        <id>49</id>
        <im_id>60793701</im_id>
        <name>BICILLIN L-A</name>
        <price>55.58</price>
        <qty>915</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>4</id>
    <name>Topiczoom</name>
    <address>
      <street>John Wall</street>
      <city>Pagaden</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>1</qty>
      </item>
      <item>
        <id>6</id>
        <im_id>11822073</im_id>
        <name>miconazole 1</name>
        <price>73.35</price>
        <qty>81</qty>
      </item>
      <item>
        <id>7</id>
        <im_id>51393666</im_id>
        <name>Nevi (Mole) Control</name>
        <price>96.86</price>
        <qty>617</qty>
      </item>
      <item>
        <id>8</id>
        <im_id>60512629</im_id>
        <name>KALI BICHROMICUM</name>
        <price>15.60</price>
        <qty>400</qty>
      </item>
      <item>
        <id>9</id>
        <im_id>68788973</im_id>
        <name>TOPIRAMATE</name>
        <price>48.58</price>
        <qty>872</qty>
      </item>
      <item>
        <id>12</id>
        <im_id>00540097</im_id>
        <name>Oxcarbazepine</name>
        <price>18.86</price>
        <qty>310</qty>
      </item>
      <item>
        <id>14</id>
        <im_id>36987288</im_id>
        <name>Virginia Live Oak</name>
        <price>36.96</price>
        <qty>628</qty>
      </item>
      <item>
        <id>17</id>
        <im_id>33992113</im_id>
        <name>anti-dandruff</name>
        <price>18.73</price>
        <qty>593</qty>
      </item>
      <item>
        <id>18</id>
        <im_id>53645147</im_id>
        <name>Ferrum Metallicum</name>
        <price>67.92</price>
        <qty>346</qty>
      </item>
      <item>
        <id>26</id>
        <im_id>68012054</im_id>
        <name>Zegerid</name>
        <price>17.08</price>
        <qty>433</qty>
      </item>
      <item>
        <id>31</id>
        <im_id>52125461</im_id>
        <name>GENTAMICIN SULFATE</name>
        <price>93.43</price>
        <qty>502</qty>
      </item>
      <item>
        <id>32</id>
        <im_id>68012490</im_id>
        <name>Fenoglide</name>
        <price>41.31</price>
        <qty>558</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>1</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>19</qty>
      </item>
      <item>
        <id>48</id>
        <im_id>04060366</im_id>
        <name>HYDROCODONE BITARTRATE AND ACETAMINOPHEN</name>
        <price>54.18</price>
        <qty>308</qty>
      </item>
      <item>
        <id>50</id>
        <im_id>07033154</im_id>
        <name>Bleomycin</name>
        <price>49.68</price>
        <qty>67</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>5</id>
    <name>Wordpedia</name>
    <address>
      <street>Ridgeview</street>
      <city>Sumberjati</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>9</qty>
      </item>
      <item>
        <id>3</id>
        <im_id>52549414</im_id>
        <name>Meprobamate</name>
        <price>11.64</price>
        <qty>379</qty>
      </item>
      <item>
        <id>4</id>
        <im_id>54868007</im_id>
        <name>MECLIZINE HYDROCHLORIDE</name>
        <price>54.49</price>
        <qty>828</qty>
      </item>
      <item>
        <id>5</id>
        <im_id>24658312</im_id>
        <name>Doxycycline Hyclate</name>
        <price>28.99</price>
        <qty>104</qty>
      </item>
      <item>
        <id>6</id>
        <im_id>11822073</im_id>
        <name>miconazole 1</name>
        <price>73.35</price>
        <qty>914</qty>
      </item>
      <item>
        <id>7</id>
        <im_id>51393666</im_id>
        <name>Nevi (Mole) Control</name>
        <price>96.86</price>
        <qty>526</qty>
      </item>
      <item>
        <id>9</id>
        <im_id>68788973</im_id>
        <name>TOPIRAMATE</name>
        <price>48.58</price>
        <qty>929</qty>
      </item>
      <item>
        <id>12</id>
        <im_id>00540097</im_id>
        <name>Oxcarbazepine</name>
        <price>18.86</price>
        <qty>429</qty>
      </item>
      <item>
        <id>15</id>
        <im_id>67510150</im_id>
        <name>Night Time Cold/Flu Relief Cherry</name>
        <price>92.26</price>
        <qty>297</qty>
      </item>
      <item>
        <id>21</id>
        <im_id>30142112</im_id>
        <name>Kroger DayTime Flu plus Severe Cold and Cough</name>
        <price>88.69</price>
        <qty>203</qty>
      </item>
      <item>
        <id>28</id>
        <im_id>49230191</im_id>
        <name>DELFLEX</name>
        <price>38.96</price>
        <qty>765</qty>
      </item>
      <item>
        <id>30</id>
        <im_id>05361945</im_id>
        <name>RULOX REGULAR</name>
        <price>17.76</price>
        <qty>211</qty>
      </item>
      <item>
        <id>31</id>
        <im_id>52125461</im_id>
        <name>GENTAMICIN SULFATE</name>
        <price>93.43</price>
        <qty>257</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>6</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>14</qty>
      </item>
      <item>
        <id>36</id>
        <im_id>29565200</im_id>
        <name>Sunscreen</name>
        <price>55.70</price>
        <qty>51</qty>
      </item>
      <item>
        <id>37</id>
        <im_id>64942122</im_id>
        <name>Dove Men plus Care</name>
        <price>41.28</price>
        <qty>218</qty>
      </item>
      <item>
        <id>47</id>
        <im_id>63481617</im_id>
        <name>OPANA</name>
        <price>46.71</price>
        <qty>267</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>6</id>
    <name>Wordify</name>
    <address>
      <street>Toban</street>
      <city>Banjar Serangan</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>3</qty>
      </item>
      <item>
        <id>5</id>
        <im_id>24658312</im_id>
        <name>Doxycycline Hyclate</name>
        <price>28.99</price>
        <qty>117</qty>
      </item>
      <item>
        <id>8</id>
        <im_id>60512629</im_id>
        <name>KALI BICHROMICUM</name>
        <price>15.60</price>
        <qty>772</qty>
      </item>
      <item>
        <id>10</id>
        <im_id>60429082</im_id>
        <name>Glipizide</name>
        <price>12.62</price>
        <qty>453</qty>
      </item>
      <item>
        <id>13</id>
        <im_id>67345078</im_id>
        <name>4 in 1 Pressed Mineral SPF 15 Porcelain</name>
        <price>62.04</price>
        <qty>249</qty>
      </item>
      <item>
        <id>16</id>
        <im_id>53942326</im_id>
        <name>Tartar Control Plus</name>
        <price>50.96</price>
        <qty>922</qty>
      </item>
      <item>
        <id>17</id>
        <im_id>33992113</im_id>
        <name>anti-dandruff</name>
        <price>18.73</price>
        <qty>394</qty>
      </item>
      <item>
        <id>18</id>
        <im_id>53645147</im_id>
        <name>Ferrum Metallicum</name>
        <price>67.92</price>
        <qty>170</qty>
      </item>
      <item>
        <id>24</id>
        <im_id>52731704</im_id>
        <name>Anxiety Complex</name>
        <price>14.11</price>
        <qty>464</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>2</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>5</qty>
      </item>
      <item>
        <id>37</id>
        <im_id>64942122</im_id>
        <name>Dove Men plus Care</name>
        <price>41.28</price>
        <qty>516</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>733</qty>
      </item>
      <item>
        <id>40</id>
        <im_id>52959692</im_id>
        <name>misoprostol</name>
        <price>6.92</price>
        <qty>180</qty>
      </item>
      <item>
        <id>45</id>
        <im_id>60505287</im_id>
        <name>Ropinirole</name>
        <price>7.24</price>
        <qty>362</qty>
      </item>
      <item>
        <id>48</id>
        <im_id>04060366</im_id>
        <name>HYDROCODONE BITARTRATE AND ACETAMINOPHEN</name>
        <price>54.18</price>
        <qty>958</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>7</id>
    <name>Blogpad</name>
    <address>
      <street>Monica</street>
      <city>Nusajaya</city>
      <country>Malaysia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>2</qty>
      </item>
      <item>
        <id>3</id>
        <im_id>52549414</im_id>
        <name>Meprobamate</name>
        <price>11.64</price>
        <qty>156</qty>
      </item>
      <item>
        <id>5</id>
        <im_id>24658312</im_id>
        <name>Doxycycline Hyclate</name>
        <price>28.99</price>
        <qty>304</qty>
      </item>
      <item>
        <id>12</id>
        <im_id>00540097</im_id>
        <name>Oxcarbazepine</name>
        <price>18.86</price>
        <qty>433</qty>
      </item>
      <item>
        <id>13</id>
        <im_id>67345078</im_id>
        <name>4 in 1 Pressed Mineral SPF 15 Porcelain</name>
        <price>62.04</price>
        <qty>428</qty>
      </item>
      <item>
        <id>17</id>
        <im_id>33992113</im_id>
        <name>anti-dandruff</name>
        <price>18.73</price>
        <qty>694</qty>
      </item>
      <item>
        <id>24</id>
        <im_id>52731704</im_id>
        <name>Anxiety Complex</name>
        <price>14.11</price>
        <qty>864</qty>
      </item>
      <item>
        <id>26</id>
        <im_id>68012054</im_id>
        <name>Zegerid</name>
        <price>17.08</price>
        <qty>212</qty>
      </item>
      <item>
        <id>27</id>
        <im_id>53942502</im_id>
        <name>NIGHT-TIME</name>
        <price>91.42</price>
        <qty>358</qty>
      </item>
      <item>
        <id>28</id>
        <im_id>49230191</im_id>
        <name>DELFLEX</name>
        <price>38.96</price>
        <qty>117</qty>
      </item>
      <item>
        <id>30</id>
        <im_id>05361945</im_id>
        <name>RULOX REGULAR</name>
        <price>17.76</price>
        <qty>589</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>7</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>2</qty>
      </item>
      <item>
        <id>37</id>
        <im_id>64942122</im_id>
        <name>Dove Men plus Care</name>
        <price>41.28</price>
        <qty>854</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>613</qty>
      </item>
      <item>
        <id>42</id>
        <im_id>42195210</im_id>
        <name>Pyrilamine Maleate and Phenylephrine Hydrochloride</name>
        <price>57.93</price>
        <qty>249</qty>
      </item>
      <item>
        <id>45</id>
        <im_id>60505287</im_id>
        <name>Ropinirole</name>
        <price>7.24</price>
        <qty>48</qty>
      </item>
      <item>
        <id>49</id>
        <im_id>60793701</im_id>
        <name>BICILLIN L-A</name>
        <price>55.58</price>
        <qty>16</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>8</id>
    <name>Bluezoom</name>
    <address>
      <street>Atwood</street>
      <city>Lunyuk Ode</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>2</qty>
      </item>
      <item>
        <id>13</id>
        <im_id>67345078</im_id>
        <name>4 in 1 Pressed Mineral SPF 15 Porcelain</name>
        <price>62.04</price>
        <qty>886</qty>
      </item>
      <item>
        <id>16</id>
        <im_id>53942326</im_id>
        <name>Tartar Control Plus</name>
        <price>50.96</price>
        <qty>674</qty>
      </item>
      <item>
        <id>25</id>
        <im_id>49288012</im_id>
        <name>Cattle Hair</name>
        <price>51.02</price>
        <qty>144</qty>
      </item>
      <item>
        <id>27</id>
        <im_id>53942502</im_id>
        <name>NIGHT-TIME</name>
        <price>91.42</price>
        <qty>711</qty>
      </item>
      <item>
        <id>32</id>
        <im_id>68012490</im_id>
        <name>Fenoglide</name>
        <price>41.31</price>
        <qty>134</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>5</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>4</qty>
      </item>
      <item>
        <id>35</id>
        <im_id>50021301</im_id>
        <name>SUNZONE SPORT SUNSCREEN SPF 30</name>
        <price>85.21</price>
        <qty>632</qty>
      </item>
      <item>
        <id>36</id>
        <im_id>29565200</im_id>
        <name>Sunscreen</name>
        <price>55.70</price>
        <qty>83</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>872</qty>
      </item>
      <item>
        <id>50</id>
        <im_id>07033154</im_id>
        <name>Bleomycin</name>
        <price>49.68</price>
        <qty>37</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>9</id>
    <name>Latz</name>
    <address>
      <street>Independence</street>
      <city>Sadang Kulon</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>6</qty>
      </item>
      <item>
        <id>4</id>
        <im_id>54868007</im_id>
        <name>MECLIZINE HYDROCHLORIDE</name>
        <price>54.49</price>
        <qty>913</qty>
      </item>
      <item>
        <id>9</id>
        <im_id>68788973</im_id>
        <name>TOPIRAMATE</name>
        <price>48.58</price>
        <qty>594</qty>
      </item>
      <item>
        <id>13</id>
        <im_id>67345078</im_id>
        <name>4 in 1 Pressed Mineral SPF 15 Porcelain</name>
        <price>62.04</price>
        <qty>772</qty>
      </item>
      <item>
        <id>15</id>
        <im_id>67510150</im_id>
        <name>Night Time Cold/Flu Relief Cherry</name>
        <price>92.26</price>
        <qty>815</qty>
      </item>
      <item>
        <id>16</id>
        <im_id>53942326</im_id>
        <name>Tartar Control Plus</name>
        <price>50.96</price>
        <qty>988</qty>
      </item>
      <item>
        <id>20</id>
        <im_id>16590303</im_id>
        <name>Liothyronine Sodium</name>
        <price>52.90</price>
        <qty>4</qty>
      </item>
      <item>
        <id>21</id>
        <im_id>30142112</im_id>
        <name>Kroger DayTime Flu plus Severe Cold and Cough</name>
        <price>88.69</price>
        <qty>589</qty>
      </item>
      <item>
        <id>30</id>
        <im_id>05361945</im_id>
        <name>RULOX REGULAR</name>
        <price>17.76</price>
        <qty>971</qty>
      </item>
      <item>
        <id>33</id>
        <im_id>57894071</im_id>
        <name>Simponi</name>
        <price>1.30</price>
        <qty>10</qty>
      </item>
      <item>
        <id>34</id>
        <im_id>49527997</im_id>
        <name>ACNE SOLUTIONS</name>
        <price>51.91</price>
        <qty>12</qty>
      </item>
      <item>
        <id>35</id>
        <im_id>50021301</im_id>
        <name>SUNZONE SPORT SUNSCREEN SPF 30</name>
        <price>85.21</price>
        <qty>286</qty>
      </item>
      <item>
        <id>39</id>
        <im_id>05170410</im_id>
        <name>Vasopressin</name>
        <price>85.02</price>
        <qty>675</qty>
      </item>
      <item>
        <id>41</id>
        <im_id>36987225</im_id>
        <name>Jute</name>
        <price>31.03</price>
        <qty>616</qty>
      </item>
      <item>
        <id>42</id>
        <im_id>42195210</im_id>
        <name>Pyrilamine Maleate and Phenylephrine Hydrochloride</name>
        <price>57.93</price>
        <qty>278</qty>
      </item>
      <item>
        <id>44</id>
        <im_id>76420780</im_id>
        <name>Multi-Specialty Kit</name>
        <price>23.04</price>
        <qty>948</qty>
      </item>
      <item>
        <id>45</id>
        <im_id>60505287</im_id>
        <name>Ropinirole</name>
        <price>7.24</price>
        <qty>749</qty>
      </item>
      <item>
        <id>46</id>
        <im_id>05271905</im_id>
        <name>Zidovudine</name>
        <price>47.05</price>
        <qty>93</qty>
      </item>
      <item>
        <id>48</id>
        <im_id>04060366</im_id>
        <name>HYDROCODONE BITARTRATE AND ACETAMINOPHEN</name>
        <price>54.18</price>
        <qty>508</qty>
      </item>
      <item>
        <id>49</id>
        <im_id>60793701</im_id>
        <name>BICILLIN L-A</name>
        <price>55.58</price>
        <qty>817</qty>
      </item>
    </items>
  </warehouse>
  <warehouse>
    <id>10</id>
    <name>Cogibox</name>
    <address>
      <street>Declaration</street>
      <city>Sambong</city>
      <country>Indonesia</country>
    </address>
    <items>
      <item>
        <id>2</id>
        <im_id>00851287</im_id>
        <name>SYLATRON</name>
        <price>80.22</price>
        <qty>7</qty>
      </item>
      <item>
        <id>4</id>
        <im_id>54868007</im_id>
        <name>MECLIZINE HYDROCHLORIDE</name>
        <price>54.49</price>
        <qty>407</qty>
      </item>
      <item>
        <id>5</id>
        <im_id>24658312</im_id>
        <name>Doxycycline Hyclate</name>
        <price>28.99</price>
        <qty>582</qty>
      </item>
      <item>
        <id>6</id>
        <im_id>11822073</im_id>
        <name>miconazole 1</name>
        <price>73.35</price>
        <qty>499</qty>
      </item>
      <item>
        <id>9</id>
        <im_id>68788973</im_id>
        <name>TOPIRAMATE</name>
        <price>48.58</price>
        <qty>592</qty>
      </item>
      <item>
        <id>12</id>
        <im_id>00540097</im_id>
        <name>Oxcarbazepine</name>
        <price>18.86</price>
        <qty>886</qty>
      </item>
      <item>
        <id>16</id>
        <im_id>53942326</im_id>
        <name>Tartar Control Plus</name>
        <price>50.96</price>
        <qty>451</qty>
      </item>
      <item>